/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "feshtolgovkntzcngrww"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlc2h0b2xnb3ZrbnR6Y25ncnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MDkzNDcsImV4cCI6MjA4NDM4NTM0N30.v-GsRmU-z2UEC9oHQKQi21tgsdFj1nfMHpPTDdXjgkw"